services:
  postgres:
    image: postgres:15
    container_name: bucket-postgres
    restart: always
    environment:
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - bucket-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: bucket-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Seoul

  app:
    build: .
    container_name: bucket-app
    depends_on:
      - postgres
      - redis
    environment:
      TZ: Asia/Seoul
    env_file:
      - .env
    ports:
      - "8080:8080"

#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
#      interval: 30s
#      timeout: 5s
#      retries: 3
#      start_period: 60s

volumes:
  bucket-postgres-data: