spring:
  application:
    name: bucket-search
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST_NAME}:5432/${PSQL_DB}
    username: ${DB_USER}
    password: ${DB_PWD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  forward-headers-strategy: native

kakao:
  auth:
    client: 4rmH2UjaWu5feAMRyeJxEWTSvU1srgY0
    redirect: http://localhost:8080/auth/login/kakao

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-ms: ${JWT_ACCESS_TOKEN_VALIDITY_MS:3600000}
  refresh-token-validity-ms: ${JWT_REFRESH_TOKEN_VALIDITY_MS:1209600000}

springdoc:
  swagger-ui:
    with-credentials: true
    tags-sorter: alpha
    operations-sorter: alpha
